### ISSUE TITLE
Escape regexp metachar when search content from marked region.

### ISSUE THREAD

**Issue by zw963** [yasuyk/helm-git-grep#18] opened 2016-04-24 07:25 UTC
Following is a example:

![](http://zw963.github.io/recorded1870927764.gif)

**Comment by yasuyk** [comment] 2016-07-22 10:20
@zw963 The issue is the feature of `helm`. So it is not beyond the scope of `helm-git-grep`. Please report this to [helm's issue tracker](https://github.com/emacs-helm/helm/issues). Closing this.

**Closed by yasuyk** 2016-07-22 10:20 UTC
